resource "random_pet" "suffix" {
  length = 2
}

resource "random_password" "api_key" {
  length  = 24
  special = false
}

# count turns one block into N resources, addressed as [0], [1], [2]
resource "local_file" "node_config" {
  count    = var.instance_count
  filename = "${path.module}/generated/node-${count.index}.conf"
  content  = <<-EOT
    # generated by terraform, do not edit
    project     = ${var.project_name}
    environment = ${var.environment}
    node_id     = ${count.index}
    cluster     = ${random_pet.suffix.id}
  EOT
}

resource "local_sensitive_file" "api_key" {
  filename = "${path.module}/generated/api-key.txt"
  content  = random_password.api_key.result
}
