apiVersion: v1
kind: Pod
metadata:
  name: curl-box
  namespace: svc-lab
  labels:
    app: curl-box
    tier: client
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.7.1
      command: ["sleep", "7200"]
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          cpu: "50m"
          memory: "64Mi"
